### PR TITLE
Draft - Work In Progress: Upgrading to PHPUnit 9

### PR DESCRIPTION
**Pull request by nikibst**
This is work is about upgrading phpunit 4.8 to 9.0.1.

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | no
| Breaks BC?    | Yes
| Tests pass?   | yes/no
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any

### CODE REVIEW

**Comment by tomfotherby** [comment]
Thank you for working on upgrading PHPUnit. It will be very helpful. Please can you explain this PR a bit - what is it doing? The code removed, why does it block PHPunit upgrades?

If it's ready to be merged, please can you remove the "Draft - Work In Progress" from the PR title?

Please also consider rebasing with squash. Custom edits to the Yii core are a big deal and often need to be re-applied after a core upgrade so having a single commit can be helpful.

**Comment by tomfotherby** [comment]
I noticed that Yii Version `1.1.21` has compatibility with PHPUnit 6

**Comment by tomfotherby** [comment]
I noticed that Yii Version `1.1.21` has compatibility with PHPUnit 6 which is where `PHPUnit_Framework_TestCase` is removed and replaced with `PHPUnit\Framework\TestCase` ([migrating to phpunit-6](https://thephp.cc/news/2017/02/migrating-to-phpunit-6)), which this PR is also combatting.

It seems there might be a different way round the problem than this PR. Before merging this PR, I would like to experiment with the the [compatibility.php file](https://github.com/yiisoft/yii/blob/master/tests/compatibility.php) file and figure out whether it solves the issue with `PHPUnit_Framework_TestCase` class. With any luck, we can proceed without changing yii core.

**Comment by nikibst** [comment]
thanks @tomfotherby , i'm going to try the compatibility.php fix.

**Pull request closed without merging**
